DROP DATABASE IF EXISTS SISAE;
CREATE DATABASE SISAE;
USE SISAE;

CREATE TABLE ENCUESTAS(
    ID_ENCUESTAS INT AUTO_INCREMENT,
    NOMBRE_ENCUESTA TEXT NOT NULL, 
    FECHA_ENCUESTA DATE NOT NULL,
    PRIMARY KEY (ID_ENCUESTAS) 
);

CREATE TABLE RESPUESTAS(
    ID_RESPUESTAS INT AUTO_INCREMENT,
    FK_ID_ENCUESTA INT NOT NULL,
    EMPRESA TEXT NOT NULL,
    USUARIO TEXT NOT NULL,
    FUNCIONALIDAD INT NOT NULL,
    CONFIABILIDAD INT NOT NULL,
    USABILIDAD INT NOT NULL,
    RENDIMIENTO INT NOT NULL,
    MANTENIMIENTO INT NOT NULL,
    PORTABILIDAD INT NOT NULL,
    SEGURIDAD INT NOT NULL,
    COMPATIBILIDAD INT NOT NULL,
    PRIMARY KEY (ID_RESPUESTAS),
    FOREIGN KEY (FK_ID_ENCUESTA) REFERENCES ENCUESTAS (ID_ENCUESTAS)
);
